---
- hosts: localhost
  become: yes
  tasks:
    - name: Extend the logical volume to 4g
      lvol:
        vg: rootvg
        lv: optlv
        size: 4000
        resizefs: yes
        shrink: no
